---
engines:
  golint:
    enabled: true
    checks:
      GoLint/Naming/MixedCaps:
        enabled: false
  govet:
    enabled: true
  gofmt:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
    - "**.go"
exclude_paths:
  - "examples/**/*"
  - "grifts/**/*"
  - "**/*_test.go"
  - "*_test.go"
  - "**_test.go"
  - "middleware_test.go"
