extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - mathjaxhelper.js

markdown_extensions:
  - admonition
  - def_list
  - extra
  - fenced_code
  - tables

pages:
- Home: index.md
- About: about.md
- Usage: usage.md
- Evolution models: evolution-models.md
- Clustering: clustering.md
- Presets: presets.md
- Examples: examples.md
- Contributing: contributing.md

repo_url: https://github.com/MaxHalford/gago
site_author: Max Halford
site_description: Genetic algorithm framework written in Go
site_name: gago

theme: readthedocs
